### ISSUE TITLE
include header and footer to the second post

### ISSUE THREAD

**Issue by egoroof** [vramana/blog#9]
Hi!

Here is not included header and footer: https://vramana.github.io/blog/2015/12/26/codemod-tutorial-2/

**Comment by vramana** [comment]
@egoroof This not published yet. I am getting it reviewed.

**Comment by egoroof** [comment]
Ok. I've just opened the blog and saw two posts.

**Comment by vramana** [comment]
I see it is due to the date being incorrect I guess. I'll change it.

**Comment by vramana** [comment]
I corrected it now. Thanks for reporting.
